#!/usr/bin/env python3

import requests
import sys
import json
import os
import re

# System call for Windows ANSI color support
os.system("")

pattern = re.compile("^([A-Z][0-9]+)+$")

class bcolors:
    """Pinch from https://stackoverflow.com/questions/287871/how-do-i-print-colored-text-to-the-terminal"""
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    RESET = '\033[0m'
    BOLD = '\033[1m'

def help_statement() -> None:
    """Help statement, which prints to screen when no args are passed, or when 'help' arg is passed to script"""
    usage_string=f"'{bcolors.HEADER}COMMA DELINEATED ADDRESS{bcolors.OKBLUE}'"
    example_string="'1600 Pennsylvania Avenue NW, Washington, DC'"
    
    print(f"\n{bcolors.OKGREEN}Weather Getter Script:{bcolors.RESET} retrieve the weather forecast based on an address (USA only).")

    print(f"\n{'Basic Forecast:' : >19} {bcolors.OKBLUE} weather-getter {usage_string}{bcolors.RESET}")
    print(f"{'Example:' : >19} {bcolors.OKBLUE} weather-getter {example_string}{bcolors.RESET}\n")

    print(f"{'Extended Forecast:' : >19} {bcolors.OKBLUE} weather-getter 7d {usage_string}{bcolors.RESET}")
    print(f"{'Example:' : >19} {bcolors.OKBLUE} weather-getter 7d {example_string}{bcolors.RESET}\n")
    return None

def get_coordinates(address: str) -> dict:
    """Returns latitude and longitude based on address (type string). If time permits, will account for:
        - multiple matches
        - non-matches
        - passing of non-string type args
    """
    response = requests.get(f"https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address={address}&benchmark=2020&format=json")
    coords = json.loads(response.content)['result']['addressMatches'][0]['coordinates']

    return coords

def convert_coordinates(coords: dict) -> dict:
    """Convert latitude and longitude into gridpoints weather.gov will understand"""
    response = requests.get(f"https://api.weather.gov/points/{coords['y']:.4f},{coords['x']:.4f}")
    properties = json.loads(response.content)['properties']
    gridpoints = {key: value for key, value in properties.items() if key.startswith('grid')}
    return gridpoints

def retrieve_weather(grid_values: dict) -> dict:
    """Feed weather.gov newly generated gridpoints, return local weather"""
    response = requests.get(f"https://api.weather.gov/gridpoints/{grid_values['gridId']}/{grid_values['gridX']},{grid_values['gridY']}/forecast")
    local_weather = json.loads(response.content)['properties']['periods']
    return local_weather


if len(sys.argv) == 1 or 'help' in sys.argv:
    help_statement()

elif sys.argv[1] == '7d' and isinstance(sys.argv[2], str):
    _getcoords = get_coordinates(sys.argv[2])
    _concoords = convert_coordinates(_getcoords)
    extended_local_weather = retrieve_weather(_concoords)

    print()
    for forecast in extended_local_weather:
        print(f"{bcolors.BOLD}{bcolors.OKCYAN}{forecast['name']}:{bcolors.RESET}\n{forecast['detailedForecast']}\n")
    print()

#elif isinstance(sys.argv[1], str):
elif sys.argv[1] == "_,_,_":
    _getcoords = get_coordinates(sys.argv[1])
    _concoords = convert_coordinates(_getcoords)
    current_local_weather = retrieve_weather(_concoords)

    print(f"\n{bcolors.BOLD}{bcolors.OKCYAN}{current_local_weather[0]['name']}:{bcolors.RESET}\n{current_local_weather[0]['detailedForecast']}\n")
    print(f"{bcolors.BOLD}{bcolors.OKCYAN}{current_local_weather[1]['name']}:{bcolors.RESET}\n{current_local_weather[1]['detailedForecast']}\n")

else:
    help_statement()
